ACCESS_TOKEN = 'sl.BWnJuQByJckn3J0AX499TAsgkB991dtPMmRMxpk519xXKbIUXIvPNI8vrcq6B5gLnJjxdc-gQl4kbeu9-8t_-xcRLpJLZgv06RqB0XAA6ZPbvSLtmHBcmpbFX5Fpc6_vzirruNo'
FILE_TO_UPLOAD = 'IWannaBeInDropBox.png'
RELATIVE_PATH_TO_FILE = f'res/{FILE_TO_UPLOAD}'
